spring:
  application:
    name: tour-portal
  redis:
      host: localhost
      port: 6379
      timeout: 0


server:
  port: 8082
  connection-timeout: 10000000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



com:
  xmy:
    properties:
      indexUrl: http://118.25.102.29/
      picUrl: http://118.25.102.29:8084/