spring:
  application:
    name: tour-socket
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.25.102.29:3306/tour?useUnicode=true&characterEncoding=utf8&autoReconnect=true&characterSetResults=utf8
    username: root
    password: root

  redis:
      host: 118.25.102.29
      port: 6379
      timeout: 0


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



com:
  xmy:
    properties:
      indexUrl: http://118.25.102.29/
      picUrl: http://118.25.102.29:8084/